# Generated by Django 3.2.6 on 2021-09-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0002_auto_20210920_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='модератор')),
            ],
            options={
                'verbose_name': 'модератор',
                'verbose_name_plural': 'модераторы',
            },
        ),
    ]
