# Generated by Django 3.2.6 on 2021-09-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0003_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_blogs.moderator'),
            preserve_default=False,
        ),
    ]
